apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha
  labels:
    pp: alpha
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alpha
  template:
    metadata:
      labels:
        pp: alpha
    spec:
      containers:
      - name: alpha
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beta
  labels:
    app: beta
spec:
  replicas: 2
  selector:
    matchLabels:
      app: beta
  template:
    metadata:
      labels:
        app: beta
    spec:
      containers:
      - name: beta
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: alpha-service
spec:
  selector:
    app: alpha
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: beta-service
spec:
  selector:
    app: beta
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
